id: P8BD3CFC3
initial_creation_type: input
source_metadata:
  title: Termas
  language: es
  description: 'A collection of spiritual treasures or terma (gter ma), which were
    reportedly hidden by Guru Padmasambhava and Yeshe Tsogyal, either in the earth
    and in the minds of disciples, and then revealed at the appropriate time by ‘treasure
    revealers’ or tertön (gter ston):'
  volume:
    872354a389f1431bbb4cada22c97c5f0:
      title: Daily Practice of Vajrakīla
      parent: Apang Tertön
    75ab5a959425446f9e11c2a33a3d6531:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Chöje Lingpa
    a9f3c8cf8ef549009020cd4091ab3618:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Chöje Lingpa
    c0fa15006acb4988a39e2f8f157ad31b:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Chokgyur Dechen Lingpa
    c8f9d12274714e23ace9f20094b1e612:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Chokgyur Dechen Lingpa
    2cceb72571464688ba2c119d488391f3:
      title: The Lament of Rudra
      parent: Chokgyur Dechen Lingpa
    116bc9517bba4db6bc3388d51a7e96cd:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    39005743176e4b56a545eaff3d25eea0:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    a6059e39cbb742df85206b4ac3fd296f:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    f251b8d55b7c4a7cbe792f53b5dad19d:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    a3f41ca2aeed4447b603e2f43e8b863e:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    9d12770db79246eea63f06907489d441:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Chokgyur Dechen Lingpa
    d859ff3172af4272bd8252a3d95a6fc8:
      title: Concise Daily Practice of Vajrasattva
      parent: Chokgyur Dechen Lingpa
    a7b96d5bad184384ad2e8db82e97ef88:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chokgyur Dechen Lingpa
    a40ff948b13642298d443679830f8651:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    fa43a8a1de414f56bc666821d370f41d:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Do Khyentse
    e2bfce45e96645e5a8e8b908959c9595:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    313300df366c438c97f85b99fa9584bb:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: Do Khyentse
    3cc407e37a3e4ded8d1d4da8f1eeb9e9:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: Do Khyentse
    2c20aaf9a893435c8e85f4a1779b2e4f:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    002bce7ce6a8407d82927e8d55725ea5:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Dorje Dechen Lingpa
    4cf82898e2fc487aa866e22e581aefbd:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Dudjom Lingpa
    37684fa1c08c45f4ac870c0fe6af6b7e:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Dudjom Rinpoche
    b2156677a3704647a8a91dcc14531b5d:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    81ebd64dc246489ea495b255b3c6f2cb:
      title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching
        from the Lama Sangdü'
      parent: Guru Chöwang
    892f9bb3cfaa489390f0bc001b118404:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Guru Chöwang
    388522a62cbf425aa98e3a85f22334aa:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Guru Chöwang
    f1e7707f62c042c8afdea153cf6f2d03:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Guru Chöwang
    3ab0fb0e4891499589a65fe21fa81321:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Guru Chöwang
    310e2fdf32a843739cd3f201e4be5e91:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Guru Chöwang
    ebe887990000427c9df4d560c52b3642:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Gyarong Khandro
    152d2f25c90445fa827c4c56a6c1e3c6:
      title: A Means to Pacify the Fear of Natural Disasters
      parent: Jamyang Khyentse Chökyi Lodrö
    ab1e1b3649a84cfe90ea67051fbd7375:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    08c01b450f4b4c3d9a41663918717948:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Jamyang Khyentse Wangpo
    ae4d26415a034291bcda6ad212de51ff:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    2afd8c0285644ff48a3ccabf80229df7:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Jamyang Khyentse Wangpo
    fc53f88d588240a9b191812a74e67289:
      title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
      parent: Jatsön Nyingpo
    77a5c6ace9b84808a5a6d784d136a423:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Jatsön Nyingpo
    1a0e8d15b6694cb0a9d11c6fc3eef3c3:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Jigdral Tutop Lingpa
    4d2c1b5d20f140e7a3835d6e6ab34b9a:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Jigme Lingpa
    b561e186bcd14232899afa0970d9451a:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    4ccba28d7e8c4cfda708f65baa977329:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    c7a8500012bd4aa0a81e99e57a576f1e:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Jigme Lingpa
    b33af5355a814c609a7e4afe409c7d8a:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Jigme Lingpa
    348cb2ff7bc042b3bae5ec6ce9287cb8:
      title: Brief Prayer of the Feast Gathering
      parent: Jigme Lingpa
    f8d826dfba564913922556e025ecc088:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    78c196d9b81c45c2a41dbf0be4cad65a:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Jigme Lingpa
    7ec6344bd5bb4b67a41dd9c0c3b5d4c8:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Jigme Lingpa
    ec04e545657a4e8bbcaae3a749eb005f:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: Jigme Lingpa
    7acef5cb6e4240098748d0039dbc9174:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Jigme Lingpa
    51223d6bfeef4ea18c365355b69ef56d:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Jigme Lingpa
    9cd5fdbae3fc45fcaba7d417fda391b2:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Jigme Lingpa
    ce0de499cd6a45c999e3c6f3dbf46191:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Jigme Lingpa
    5fec13cc1a474b55a0f531568f80516b:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Jigme Lingpa
    deaabc8ae4024ded8569c1131d9c8e3a:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Jigme Lingpa
    1fd06dc15d0e440cb5a3c5741ae257ea:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Jigme Lingpa
    3080c33018fa40a391e21703b64594a0:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Jigme Lingpa
    dcb873666e624fa3a22913c36c619cc5:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Jigme Lingpa
    06e422c59aba43119a71cb12074e3666:
      title: Vajra Verses on the Natural State
      parent: Jigme Lingpa
    2f7a93960ee34b67abeaa4cef92d375c:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Karma Lingpa
    3175c3e3259c478bb1bab08e57fad220:
      title: The Benefits of the Vajra Guru Mantra and an Explanation of Its Syllables
      parent: Karma Lingpa
    9e0bf62f6ed049b3892011c7f0e1197e:
      title: The Root Verses on the Six Bardos
      parent: Karma Lingpa
    f1f5e05e8db94ff699a29268d3c66d60:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Khenchen Jigme Phuntsok
    1dd27a0f27484e0aaafdd65516815c11:
      title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious
        Dorje Drolö'
      parent: Khenchen Jigme Phuntsok
    75a78b6308204ee993b358a6a2f46aed:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Lhatsün Namkha Jigme
    53ffed14dc0a4dd7af7e534ce74ee07c:
      title: Maṇḍala Offering from Longsal Dorje Nyingpo
      parent: Longsal Nyingpo
    480c71754f254f85b8a7387e4e2cb5df:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Ngakchang Shakya Zangpo
    182e9f64992b40958df1dd984fc410d7:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Nyala Pema Dündul
    dd93b95b39c841dc9ae451e07373ae8e:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    ff9557a3943b409c8c40f64c2f4c5939:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    81f55dd15ae04a98b3c89dd9d997ff6c:
      title: The Pointing-the-Staff Instruction
      parent: Nyang Ral Nyima Özer
    a030b368cee54c1abaeb00550f334dca:
      title: A Concise History of Orgyen Padma’s Enlightened Deeds
      parent: Orgyen Lingpa
    bcf3339e24834ef0a385e745fff3df22:
      title: Yeshe Tsogyal's Prayer
      parent: Pema Lingpa
    56bf38a7b8ac419ba56e0fce51b8bbc7:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Ratna Lingpa
    50933d144000406ca42861890f5fbfb3:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Rigdzin Gödem
    f9fc303b70bc43568677dda27b96f5e5:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Rigdzin Gödem
    230bebc124db454d97ebd11d8aa552f3:
      title: 'Marmé Mönlam: The Light Offering Prayer'
      parent: Rigdzin Nyima Drakpa
    151e751c0b78404192116c7beaea7901:
      title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
      parent: Samten Lingpa
    9ae3c0aa39684cb1a12f2ebe5336918a:
      title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart
        Essence of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
      parent: Sera Khandro
    a5a1f61e289d45528b864b8ac08d0032:
      title: 'The Profound Bestowal of Blessings: A Sādhana of Dorje Drolö from the
        Reality Ḍākinīs'' Secret Treasury (Chönyi Khandrö Sangdzö)'
      parent: Sera Khandro
    a2357bf48c03497eb0eceb3838152fd7:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Sherab Özer
    ad2673a1eec74651a829c39715ab66a9:
      title: Brief Sukhāvatī Aspiration
      parent: Tertön Mingyur Dorje
    11627e56fcda47f9b6ff4c62c9a0e4df:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Tertön Mingyur Dorje
    dec91d1db22b434b9d27528a3801f399:
      title: Prayer to Behold Amitābha in Dreams
      parent: Tertön Mingyur Dorje
    fe269329a8e44b2293e1404756df430b:
      title: 'Inventory: The Perfectly Clear Mirror from the Razor of the Innermost
        Essence'
      parent: Tertön Sogyal
    081dd9b002e441f19c7d6fb72d9e1536:
      title: Sādhana of Mañjughoṣa
      parent: Tertön Sogyal
    895c90d535214dbfa67bb17203c1808a:
      title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
      parent: Tertön Sogyal
    89503a1f0524491da28c0bf7ff43c059:
      title: The Guru Yoga of the Profound Path
      parent: Tertön Sogyal
    33566dfc343e4b6eb6b64e2d713d5f94:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Tertön Sogyal
    65194d80f28043c5b9f731041a95958c:
      title: The Summoning of Blessings which Brings them Swift and Fast
      parent: Tertön Sogyal
    dfb3b26496f0459288f831e90946a07c:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Tertön Sogyal
    bf65c06e832b43db8dccaad3e53836d2:
      title: The Wisdom Mind Practice of One Kīla
      parent: Tertön Sogyal
    64fde21cd22b4134a1286ee1a8eb708e:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Tulku Zangpo Drakpa
    5d9eec8be67741c5b4446621e14b157b:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Tulku Zangpo Drakpa
    ddf52ef3f900480498f1275a66726b10:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Tulku Zangpo Drakpa
    5656a4aa89a24c6cb0df92f31002ccc3:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Tulku Zangpo Drakpa
    9f4753a567a34c9cb35291407ba8a12a:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Tulku Zangpo Drakpa
    69dbd5afa46f47c98ed6bae50b343985:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Tulku Zangpo Drakpa
    3ed92f1e70f34f79a7dcbaaf897b1ff7:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Tulku Zangpo Drakpa
    6649861862db4949b722cd41a5b1dba2:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Tulku Zangpo Drakpa
created_at: '2022-03-01T06:17:48.624002'
last_modified_at: '2022-03-01T06:17:48.624004'
